# Generated by Django 2.2.24 on 2022-04-04 12:12

from django.db import migrations


def define_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    if not flat_set.exists():
        return None
    for flat in flat_set.iterator():
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(define_new_building),
    ]
