# Generated by Django 2.2.24 on 2022-04-08 10:02

from django.db import migrations


def move_owners_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'owner')
    owners = Owner.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners_info, move_backward),
    ]
